services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
#      - DATABASE_HOST=db
#      - DATABASE_USER=postgres
#      - DATABASE_PASSWORD=password
#      - DATABASE_NAME=myapp_development
